### ISSUE TITLE
Deploy from master is broken

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/weather-app#167]
In #154 I added an Action to execute `npm run deploy` when the master branch is updated (from a merged PR). Unfortunately, it didn't work. I'm getting this error:

```
aborted: problem committing directory to local branch
```

I think the crux of the problem is that we need to supply the action with a token that's authorized to push to the gh-pages branch.

This issue is to research the correct solution.

**Comment by dave-burke** [comment]
This looks promising: https://github.com/marketplace/actions/deploy-to-github-pages

Replace `- run: npm run deploy` with:

```
- name: Deploy
  uses: JamesIves/github-pages-deploy-action@3.7.1
  with:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    BRANCH: gh-pages # The branch the action should deploy to.
    FOLDER: dist # The folder the action should deploy.
    CLEAN: true # Automatically remove deleted files from the deploy branch
```

and remove the use of `push-dir`.

GitHub automatically [provides](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret) the `GITHUB_TOKEN` secret.

It should be possible to test this by (temporarily) changing the `on` configuration so the workflow triggers from the PR. Then once it's proven out, I can rever to `on.push.branches = [ master]` before merging.

It may *also* be possible to use this action's `TARGET_FOLDER` feature to deploy each PR to a directory, but I'll have to experiment how that works (or doesn't) with the `CLEAN` setting.
